### ISSUE TITLE
Fix: Frequent "RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)" Errors

### ISSUE THREAD

**Issue by Chrisqcwx** [vanillaer/Candidate_Pseudolabel_Learning-ICML2024#1]
# Description
I've encountered multiple instances of the following error while using the source code:
 "RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)"

# Details:
## First Occurrence:
+ File: methods/semi_supervised_learning_new/textual_PL.py
+ Line: 186
![image](https://github.com/user-attachments/assets/75dd18d0-ca3c-4355-b9ee-65e0685922fd)

To resolve this, I made a modification at line 187, which temporarily fixed the issue.

## Next Occurrence:
+ File: utils/clip_pseudolabels.py
+ Line: 387

![ITD6P)A~2Q(AM(K%8 RA17G](https://github.com/user-attachments/assets/84c6ab94-f084-4d06-ae52-697d0f412d21)

# Concern:
There may be other similar errors throughout the codebase. Could you please review and fix these issues?

Thank you for your assistance!

**Comment by vanillaer** [comment]
Hi @Chrisqcwx,

Thank you for bringing this to our attention with the CPL project. Actually, I didn't encounter the problem you mentioned. I can confirm that the code operates smoothly when following the instructions provided in the README.md, as this has been thoroughly tested.

It's possible that the issue you're experiencing is related to a different version of PyTorch/CUDA. I'm sharing a [link](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/3958)that might shed some light on this matter. One way to solve this problem is to keep the verions of the packages the same as those listed in the requirements.txt.
